from app.dlp.models import Channel, ClassificationLevel, DestinationCategory, DlpEventInput


SAMPLE_EVENTS = [
    DlpEventInput(
        channel=Channel.EMAIL,
        user="ana.silva",
        department="Comunicacao",
        destination="imprensa@example.com",
        destination_category=DestinationCategory.APPROVED_EXTERNAL,
        declared_classification=ClassificationLevel.PUBLIC,
        subject="Release publico",
        content="[PUBLICO] Release aprovado para imprensa sobre campanha institucional.",
    ),
    DlpEventInput(
        channel=Channel.EMAIL,
        user="bruno.ramos",
        department="RH",
        destination="bruno@gmail.com",
        destination_category=DestinationCategory.PERSONAL,
        declared_classification=ClassificationLevel.CONFIDENTIAL,
        subject="Planilha de salarios",
        content="[CONFIDENCIAL] Folha de pagamento com salarios e bonus do time.",
    ),
    DlpEventInput(
        channel=Channel.EMAIL,
        user="carla.nunes",
        department="Juridico",
        destination="contratos@fornecedor.example",
        destination_category=DestinationCategory.APPROVED_EXTERNAL,
        declared_classification=ClassificationLevel.CONFIDENTIAL,
        subject="Contrato fornecedor",
        content="[CONFIDENCIAL] Contrato comercial para revisao do fornecedor aprovado.",
    ),
    DlpEventInput(
        channel=Channel.UPLOAD,
        user="gabriela.rocha",
        department="Marketing",
        destination="Portal institucional",
        destination_category=DestinationCategory.APPROVED_EXTERNAL,
        declared_classification=ClassificationLevel.PUBLIC,
        subject="campanha-publica.txt",
        content="[PUBLICO] Campanha institucional aprovada para publicacao externa.",
    ),
    DlpEventInput(
        channel=Channel.UPLOAD,
        user="diego.lima",
        department="Vendas",
        destination="Drive pessoal",
        destination_category=DestinationCategory.PERSONAL,
        declared_classification=ClassificationLevel.INTERNAL,
        subject="base-clientes.csv",
        content="Clientes: 123.456.789-09, 987.654.321-00, 111.222.333-44",
    ),
    DlpEventInput(
        channel=Channel.UPLOAD,
        user="elisa.moraes",
        department="TI",
        destination="Repositorio publico",
        destination_category=DestinationCategory.PUBLIC_SERVICE,
        declared_classification=ClassificationLevel.INTERNAL,
        subject="config.env",
        content="api_key = sk_live_1234567890abcdef",
    ),
    DlpEventInput(
        channel=Channel.CHAT,
        user="helena.martins",
        department="Comunicacao",
        destination="Chat corporativo",
        destination_category=DestinationCategory.INTERNAL,
        declared_classification=ClassificationLevel.PUBLIC,
        subject="Resumo de politica publica",
        content="[PUBLICO] Resuma a politica publica de privacidade publicada no site.",
    ),
    DlpEventInput(
        channel=Channel.CHAT,
        user="felipe.costa",
        department="Atendimento",
        destination="IA publica",
        destination_category=DestinationCategory.PUBLIC_SERVICE,
        declared_classification=ClassificationLevel.PUBLIC,
        subject="Prompt de atendimento",
        content="Gere resposta para cliente joao@example.com com CPF 123.456.789-09.",
    ),
    DlpEventInput(
        channel=Channel.CHAT,
        user="ivan.almeida",
        department="Financeiro",
        destination="IA publica",
        destination_category=DestinationCategory.PUBLIC_SERVICE,
        declared_classification=ClassificationLevel.INTERNAL,
        subject="Analise de planilha com CPFs",
        content="Analise estes registros: 123.456.789-09, 987.654.321-00, 111.222.333-44.",
    ),
]
